GNUmakefile: compile enet.cpp only if NETCODE!=0.
Background: gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
I'm getting a missing compiler-provided symbol:

 /usr/bin/ld: obj/build/enet.o: in function `enet_time_get':
 source/build/include/enet.h:4948: undefined reference to `__atomic_load_8'
 /usr/bin/ld: source/build/include/enet.h:4958: undefined reference to `__atomic_compare_exchange_8'
 collect2: error: ld returned 1 exit status

so have a means of omitting the object file when it is not actually needed.